import json
from pathlib import Path
from .assessment import validate_assessment
from .schemas import Assessment, Attempt, Claim, Context, Evidence, Review, ReviewInput, Source


def demo_review():
    sources = [Source.model_validate(s) for s in json.loads((Path(__file__).resolve().parent.parent/'data/demo_sources.json').read_text())]
    claim = Claim(original_span='More fluorescent puncta indicate increased autophagic activity.', text='More fluorescent puncta indicate increased autophagic activity.', type='mixed', observations=['Synthetic reported observation: more CYTO-ID-positive puncta at one time point.'], inferences=['The original answer infers increased autophagic activity from puncta count.'], missing_context=['Which exact kit and imaging conditions were used?', 'Was formation compared with clearance using a validated assay design?'])
    claim.assessment = Assessment(status='Insufficient evidence found', evidence=[Evidence(source_id=s.source_id,passage=s.passages[0].text,location=s.passages[0].location,relationship='limitation') for s in sources], explanation='Curated interpretation: more visible compartments is a snapshot of abundance. Autophagic flux means the rate at which material moves through the degradation pathway. A larger pool could reflect increased formation, reduced clearance, or both. These short public extracts do not resolve the synthetic sample’s flux direction.', context_mismatches=['The synthetic comparison has one time point and no lysosomal-inhibition comparison; the manufacturer discusses flux under inhibition.'], limitations=['Demonstration — not a live verification or an actual experimental result.', 'Only the Loos abstract and a short manufacturer-page extract were available here; full methods and a product manual were not reviewed.', 'A suggested comparison does not by itself guarantee a mechanistic conclusion.'], suggested_wording='The sample showed more CYTO-ID-positive puncta under the measured conditions. This observation alone does not establish whether autophagic flux increased or decreased.', next_verification_step='Could an appropriately validated comparison of control and test conditions, each with and without lysosomal inhibition, help investigate formation and clearance? Review the exact kit, conditions, and interpretation with a knowledgeable researcher.')
    review = Review(mode='demo',original_input=ReviewInput(text=claim.text,intended_use='assay interpretation',context=Context(assay='CYTO-ID',conditions='Synthetic samples; one time point; no lysosomal-inhibition comparison.')),missing_fields=['organism_model','reagent'],extraction_method='Curated demonstration; no runtime AI extraction',claims=[claim],sources=sources,notices=['Reconstructed example, not an authenticated historical ChatGPT quotation.', 'Source extracts archived from actual public retrieval on 2026-09-16; opening the demo makes no external request.', 'No real cell identities, measurements, images, treatment outcomes, or private research are included.'])
    for s in sources:
        review.attempts.append(Attempt(retrieval_run_id=s.retrieval_run_id,claim_id=claim.claim_id,query_or_url=s.url,adapter=s.category,access_state='partial_access',timestamp=s.retrieved_at,detail='Archived short extract for curated demonstration; not a new live retrieval.',source_ids=[s.source_id]))
    review.validation_results = validate_assessment(claim.assessment, sources)
    return review
